document.querySelector('#submit').onclick = function() {
    document.getElementById('submit').style.background = 'orange';
    document.getElementById("p").style.color = 'red';
    document.getElementById("p2").style.color = 'red';
    document.getElementById("p3").style.color = 'red';
    document.getElementById("p4").style.color = 'red';
    document.getElementById("p5").style.color = 'red';
    document.getElementById("p6").style.color = 'red';
    document.getElementById("p7").style.color = 'red';
    document.getElementById("p8").style.color = 'red';
    document.getElementById("p9").style.color = 'red';
    document.getElementById("h2").style.color = 'green';
    document.getElementById("a1").style.color = 'green';
    document.getElementById("a2").style.color = 'green';
    document.body.style.background = 'black';
}
document.querySelector('#submit2').onclick = function() {
    document.getElementById('submit2').style.background = 'yellow';
    document.getElementById("p").style.color = 'black';
    document.getElementById("p2").style.color = 'black';
    document.getElementById("p3").style.color = 'black';
    document.getElementById("p4").style.color = 'black';
    document.getElementById("p5").style.color = 'black';
    document.getElementById("p6").style.color = 'black';
    document.getElementById("p7").style.color = 'black';
    document.getElementById("p8").style.color = 'black';
    document.getElementById("p9").style.color = 'black';
    document.getElementById("h2").style.color = 'black';
    document.getElementById("a1").style.color = 'black';
    document.getElementById("a2").style.color = 'black';
    document.body.style.background = 'white';
}